<RegistrationWindow@Screen>:
    name: "registration"
    Screen:
        BoxLayout:
            orientation: "vertical"
            spacing: "10dp"
            MDLabel:
                text: "Registration Page"
                halign: "center"
            MDRaisedButton:
                text: "Back to Login"
                pos_hint: {"center_x": 0.5}
                on_press: app.define_direction_switch_page("login")